set -g mouse on
set -g set-clipboard on
set-option -g allow-rename off
set -g history-limit 10000
set -g focus-events on
set -sg escape-time 0

set -g allow-rename off

set -g default-terminal "tmux-256color"
set-option -g default-shell "/bin/zsh" 

# ===[ APPEARANCE ]===
set -g status-position top

# The whole bar
set -g status-left " "
set -g status-right " "
set -g status-style "fg=#C4A7E7"
set -g status-justify "centre"

set -g pane-border-style fg='#ebbcba'
set -g pane-active-border-style fg='#ebbcba'
set -g display-panes-active-colour '#ebbcba'
set -g display-panes-colour '#ebbcba'


# Window indicators
setw -g window-status-style  "fg=#dddddd"
setw -g window-status-format " #I:#W"

setw -g window-status-current-format " #I:#W"
set -g window-status-current-style "fg=#ebbcba",bold

#####
#####
#####
#####


# ===[ KEYBINDS ]===
# Prefix
unbind C-b
set -g prefix C-s
bind C-s send-prefix

unbind-key r
bind-key r source-file ~/.config/tmux/tmux.conf

# Copying
set-window-option -g mode-keys vi
bind-key [ copy-mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"

# Panes
unbind %
unbind '"'
bind-key -n C-h select-pane -L
bind-key -n C-j select-pane -D
bind-key -n C-k select-pane -U
bind-key -n C-l select-pane -R

bind "'" split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
